from __future__ import annotations

DEFAULT_DESTINATION = "Chicago"
DEFAULT_BUDGET_USD = 2200.0
DEFAULT_TRAVEL_STYLE = "balanced"
DEFAULT_INTERESTS = ["food", "culture"]
DEFAULT_GROUP_SIZE = 1
DEFAULT_TRIP_DAYS = 7

# US-only airport defaults for flight search.
DEFAULT_DEPARTURE_ID = "LAX"
DEFAULT_ARRIVAL_ID = "ORD"

DEFAULT_OPENAI_MODEL = "gpt-4o-mini"
DEFAULT_MAX_SEARCH_RESULTS = 6
MIN_MAX_SEARCH_RESULTS = 3
MAX_MAX_SEARCH_RESULTS = 12

DEFAULT_GEOAPIFY_DINING_RADIUS_M = 8000
DEFAULT_GEOAPIFY_PLACES_RADIUS_M = 40000
DEFAULT_GEOAPIFY_HOTEL_RADIUS_M = 8000
MIN_GEOAPIFY_DINING_RADIUS_M = 1000
MAX_GEOAPIFY_DINING_RADIUS_M = 50_000

DEFAULT_DINING_MAX_RESULTS = 30
MIN_DINING_MAX_RESULTS = 5
MAX_DINING_MAX_RESULTS = 100

DEFAULT_PLACES_MAX_RESULTS = 40
MIN_PLACES_MAX_RESULTS = 5
MAX_PLACES_MAX_RESULTS = 60

DEFAULT_FLIGHT_MAX_RESULTS = 12
MIN_FLIGHT_MAX_RESULTS = 5
MAX_FLIGHT_MAX_RESULTS = 25

DEFAULT_SHOW_MAX_RESULTS = 12
MIN_SHOW_MAX_RESULTS = 3
MAX_SHOW_MAX_RESULTS = 30

